@tool
class_name LivePaletteSet
extends RefCounted

const DIR := "res://live_palette"
const DEFAULT_STEM := "palette"

var palettes: Dictionary = {}


func load_all() -> void:
	palettes.clear()
	if not DirAccess.dir_exists_absolute(DIR):
		return
	var stems: Array = []
	for file in DirAccess.get_files_at(DIR):
		if file.get_extension() == "tres":
			stems.append(file.get_basename())
	stems.sort()
	for stem in stems:
		var data: LivePaletteData = load("%s/%s.tres" % [DIR, stem]) as LivePaletteData
		if data != null:
			palettes[stem] = data


func stems() -> Array:
	var out: Array = palettes.keys()
	out.sort()
	if DEFAULT_STEM in out:
		out.erase(DEFAULT_STEM)
		out.push_front(DEFAULT_STEM)
	return out


func get_palette(p_stem: String) -> LivePaletteData:
	return palettes.get(p_stem)


func is_empty() -> bool:
	return palettes.is_empty()


func apply_to_tree(p_root: Node, p_dirty_files: Dictionary = {}) -> int:
	var changed := 0
	for stem in palettes:
		changed += (palettes[stem] as LivePaletteData).apply_to_tree(p_root, p_dirty_files)
	return changed


func apply_to_object(p_object: Object, p_visited: Dictionary, p_dirty_files: Dictionary = {}) -> int:
	var changed := 0
	for stem in palettes:
		changed += (palettes[stem] as LivePaletteData).apply_to_object(p_object, p_visited.duplicate(), p_dirty_files)
	return changed


func find_entry(p_id: String) -> Dictionary:
	for stem in stems():
		var data: LivePaletteData = palettes[stem]
		var index := data.find_index(p_id)
		if index >= 0:
			return {"stem": stem, "palette": data, "index": index}
	return {}


func get_color_by_id(p_id: String) -> Color:
	var found := find_entry(p_id)
	if found.is_empty():
		return Color.WHITE
	return (found["palette"] as LivePaletteData).get_color_by_id(p_id)


func get_color_by_name(p_name: StringName, p_stem: String = "") -> Color:
	if p_stem != "" and palettes.has(p_stem):
		return (palettes[p_stem] as LivePaletteData).get_color_by_name(p_name)
	for stem in stems():
		var data: LivePaletteData = palettes[stem]
		if data.has_color_name(p_name):
			return data.get_color_by_name(p_name)
	push_warning("LivePalette: no color named '%s' in any palette" % p_name)
	return Color.WHITE


func has_color_name(p_name: StringName) -> bool:
	for stem in palettes:
		if (palettes[stem] as LivePaletteData).has_color_name(p_name):
			return true
	return false


func new_id() -> String:
	var id := Resource.generate_scene_unique_id()
	while not find_entry(id).is_empty():
		id = Resource.generate_scene_unique_id()
	return id


func repair_duplicate_ids() -> PackedStringArray:
	var repaired := PackedStringArray()
	var seen := {}
	var all_ids := PackedStringArray()
	for stem in stems():
		for entry in (palettes[stem] as LivePaletteData).entries:
			all_ids.append(str(entry["id"]))
	for stem in stems():
		var data: LivePaletteData = palettes[stem]
		for entry in data.entries:
			var id: String = str(entry["id"])
			if not seen.has(id):
				seen[id] = "%s/%s" % [stem, entry["name"]]
				continue
			var fresh := data.new_id(all_ids)
			all_ids.append(fresh)
			entry["id"] = fresh
			seen[fresh] = "%s/%s" % [stem, entry["name"]]
			if not stem in repaired:
				repaired.append(stem)
			push_warning("LivePalette: '%s' in %s.tres shared the id %s with %s, so picking it applied that other color. It now has the id %s; anything already bound to it must be picked again." % [entry["name"], stem, id, seen[id], fresh])
	return repaired


func set_variant(p_variant: String) -> int:
	var switched := 0
	for stem in palettes:
		var data: LivePaletteData = palettes[stem]
		if p_variant in data.variants:
			data.set_active_variant(p_variant)
			switched += 1
	return switched


func variant_names() -> PackedStringArray:
	var names := PackedStringArray()
	for stem in stems():
		for variant in (palettes[stem] as LivePaletteData).variants:
			if not variant in names:
				names.append(variant)
	return names


const CONST_PATH := "%s/palette_const.gd" % DIR
const CONST_CLASS := "LivePalette"

static func namespace_for(p_stem: String) -> String:
	var stem := p_stem.trim_suffix("_palette").trim_suffix("palette")
	if stem.is_empty():
		stem = p_stem
	var out := ""
	for c in stem.to_snake_case().to_upper():
		out += c if (c >= "A" and c <= "Z") or (c >= "0" and c <= "9") else "_"
	while out.contains("__"):
		out = out.replace("__", "_")
	out = out.lstrip("_").rstrip("_")
	if out.is_empty() or (out[0] >= "0" and out[0] <= "9"):
		out = "P_" + out
	return out


func build_const_script() -> String:
	var out := PackedStringArray()
	out.append("# Generated by the Live Palette addon from %s/*.tres." % DIR)
	out.append("# Do not edit — it is rewritten whenever a palette changes.")
	out.append("class_name %s" % CONST_CLASS)
	out.append("")

	var default_palette: LivePaletteData = palettes.get(DEFAULT_STEM)
	var taken := {}
	if default_palette != null:
		out.append(default_palette.build_const_body(CONST_CLASS))
		for e in default_palette.entries:
			var ident := LivePaletteData.const_identifier(str(e["name"]))
			if not ident.is_empty():
				taken[ident] = true

	for stem in stems():
		if stem == DEFAULT_STEM:
			continue
		var data: LivePaletteData = palettes[stem]
		var space := namespace_for(String(stem))
		if taken.has(space):
			push_warning("LivePalette: palette '%s' wants the name %s, which a color in the default palette already uses; exposing it as %s_ instead. Rename either to settle it." % [stem, space, space])
			space += "_"
		taken[space] = true
		out.append("")
		out.append("")
		out.append("## From %s/%s.tres." % [DIR, stem])
		out.append("class %s:" % space)
		out.append(data.build_const_body("%s.%s" % [CONST_CLASS, space], "\t"))
	return "\n".join(out) + "\n"
